version: "3.5"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssword!@#
    volumes:
      - sqlserver:/var/opt/mssql 

volumes:
  sqlserver:
      driver: local