@host=https://localhost:7005

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNjliOGM3OS00OWMwLTRkY2EtODkwMi0xMzU5NWIzYmYxMDciLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwianRpIjoiNWI1Y2NmNWItNDA1Ni00ZTM3LWIxMjYtZGNmYTE3YWZjNGNkIiwiZXhwIjoxNjYyMDU3NzEwLCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.3-ZfSpiw6pmLB_4BfJoHA3mX8zUOm5v66DIx0HzeLcU